NumPy is a library used for working with n-dimentional arrays

In [1]:
import numpy as np

### Casting List as Array

In [2]:
mylist=[1,3,5,7,9]

In [3]:
myarr=np.array(mylist)

In [5]:
myarr

array([1, 3, 5, 7, 9])

In [6]:
type(myarr)

numpy.ndarray

In [7]:
mylist=[[1,2,3],[4,5,6],[7,8,9]]
matrix=np.array(mylist)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Creating Array by built in functions

arange -> similar to range func
            Syntax - (start, stop, interval, dtype=int/float)
                        start and interval are optional

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(1,7)

array([1, 2, 3, 4, 5, 6])

In [11]:
np.arange(10,101,5)

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100])

zeroes -> fills in a array of given shape with zeroes
            Syntax - (shape,dtype=float/int)
                        shape - int for 1d array
                                tuple for nd array
                                (row,column) 2d array

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((5,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [19]:
#3d array
arr_3d = np.zeros((2,3,4),dtype=int)
arr_3d

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [20]:
arr_3d[0]

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [21]:
arr_3d[0][0]

array([0, 0, 0, 0])

ones -> similar to zeroes, fills 1s 

In [22]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
linspace -> returns array with n number of elemnts, evenly distributed with starting and ending points
                Syntax - (start, stop, n)
                            stop point is included unlike range function

In [24]:
np.linspace(10,100,num=20,) #returns 20 elements evenly distributed between 10 and 100

array([ 10.        ,  14.73684211,  19.47368421,  24.21052632,
        28.94736842,  33.68421053,  38.42105263,  43.15789474,
        47.89473684,  52.63157895,  57.36842105,  62.10526316,
        66.84210526,  71.57894737,  76.31578947,  81.05263158,
        85.78947368,  90.52631579,  95.26315789, 100.        ])

In [ ]:
eye -> returns 2d identity matrix of given size
        Syntax - (size)

In [26]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [28]:
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
random.rand -> returns random values between [0,1) for the given shape of array
                Syntax - (size) 
                            do not pass tuple for nd array size

In [29]:
np.random.rand(3)

array([0.79566469, 0.08870369, 0.52064677])

In [33]:
np.random.rand((3,5))

TypeError: 'tuple' object cannot be interpreted as an integer

In [32]:
np.random.rand(3,5)

array([[0.33558502, 0.48324624, 0.0321807 , 0.22832356, 0.61812927],
       [0.24982118, 0.45927458, 0.93679632, 0.44839557, 0.6623784 ],
       [0.07257654, 0.12808841, 0.04606118, 0.89243248, 0.09933973]])

In [ ]:
random.randn -> returns random values to constitue a standard distribution
                    standard distribution - mean = 0 
                                            variance = 1 is a measure of how far each number in dataset is from mean
                                            this can be observed with large dataset samples, not with smaller samples
                    Syntax - (size)
                        do not pass tuple for nd array size

In [34]:
np.random.randn(5)

array([ 0.39499623, -0.14983301, -1.65687193, -0.46739018, -1.18648811])

In [43]:
std_dist_arr = np.random.randn(4,2)
std_dist_arr

array([[-2.05360725,  1.13226333],
       [-0.32580294, -0.04819139],
       [-0.65429748,  0.08995753],
       [ 0.66746729,  0.60172055]])

In [44]:
std_dist_arr.mean()

-0.07381129419227196

In [45]:
std_dist_arr.var()

0.8509982327692193

In [46]:
std_dist_arr = np.random.randn(10000,3000)

In [47]:
std_dist_arr.mean()

-0.0002909408853902616

In [48]:
std_dist_arr.var()

1.0002290430692216

In [49]:
del std_dist_arr

In [ ]:
np.random.randint -> generates random integers in the given range
                        Syntax - (lower bound, upper bound, shape)

In [2]:
np.random.randint(-34,65,7)

array([ 60,  53,  -2,  22,  52, -27,  -6])

In [4]:
np.random.randint(43,142,(3,5))

array([[122,  93,  49, 129,  57],
       [ 87,  92, 126,  96, 136],
       [ 49,  59,  48,  85,  73]])

In [ ]:
seed -> generates/produces the same set of random numbers even on new run of the statement
            Syntax - np.random.seed(arbitrary_number)
                        42 is usually used by default in lot of libraries
            Note: Use both seed and generation statements in same cell, or else it wont work

In [5]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [6]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [7]:
np.random.rand(4)

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [ ]:
reshape -> convertion of array dimension
            Syntax - array.reshape(shape)

In [9]:
arr = np.random.randint(-31,54,24)
arr

array([ 30,  19,  23,  32, -29,  19, -25, -11,  41,   7, -14, -28,  28,
       -18, -23,  21, -30,  52,  28,  39,  12, -24,  15,   3])

In [10]:
arr.reshape(3,8)

array([[ 30,  19,  23,  32, -29,  19, -25, -11],
       [ 41,   7, -14, -28,  28, -18, -23,  21],
       [-30,  52,  28,  39,  12, -24,  15,   3]])

In [11]:
arr

array([ 30,  19,  23,  32, -29,  19, -25, -11,  41,   7, -14, -28,  28,
       -18, -23,  21, -30,  52,  28,  39,  12, -24,  15,   3])

In [13]:
arr.reshape(3,4,2)

array([[[ 30,  19],
        [ 23,  32],
        [-29,  19],
        [-25, -11]],

       [[ 41,   7],
        [-14, -28],
        [ 28, -18],
        [-23,  21]],

       [[-30,  52],
        [ 28,  39],
        [ 12, -24],
        [ 15,   3]]])

In [ ]:
array.max() -> returns max value
     .min() -> returns min value
     .argmax() -> returns index number of max value
     .argmin() -> returns index number of min value

### Broadcasting

We can Broadcast an array unlike list

In [3]:
mylist = [x for x in range(0,11)]
mylist

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [4]:
mylist[0:5]=100

TypeError: can only assign an iterable

In [5]:
array = np.arange(0,11)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
array[0:5] = 100
array

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

Array assignment affects Original array in case of any changes in assignment array

In [7]:
arr_copy = array[0:5]
arr_copy

array([100, 100, 100, 100, 100])

In [8]:
arr_copy[:]=69
arr_copy

array([69, 69, 69, 69, 69])

In [9]:
array

array([69, 69, 69, 69, 69,  5,  6,  7,  8,  9, 10])

In order to avoid the changes to original array, use the function .copy()

In [11]:
array_copy = array[3:8].copy()
array_copy

array([69, 69,  5,  6,  7])

In [12]:
array_copy[:]=100
array_copy

array([100, 100, 100, 100, 100])

In [13]:
array

array([69, 69, 69, 69, 69,  5,  6,  7,  8,  9, 10])

### Indexing on 2D array

In [25]:
array_2d = np.random.randint(0,100,(5,7))
array_2d

array([[45, 29, 73, 81, 92, 63, 11],
       [ 0, 69, 20, 20, 85,  6, 65],
       [66, 72, 39, 35,  9, 96,  3],
       [29, 23, 72, 82, 41, 32, 34],
       [96, 64, 58, 43, 62, 38, 19]])

In [26]:
array_2d[0,0]

45

In [27]:
array_2d[4,6]

19

In [29]:
array_2d[:4,3:]

array([[81, 92, 63, 11],
       [20, 85,  6, 65],
       [35,  9, 96,  3],
       [82, 41, 32, 34]])

### Conditional Selection

In [30]:
array = np.random.randint(0,101,10)
array

array([53, 28, 21, 70, 88, 14, 11, 86, 18, 41])

In [31]:
bool_arr = array % 2 == 0
bool_arr

array([False,  True, False,  True,  True,  True, False,  True,  True,
       False])

In [32]:
array[bool_arr]

array([28, 70, 88, 14, 86, 18])

In [33]:
array[array%2!=0]

array([53, 21, 11, 41])

## Operations

In [ ]:
 arrays can be operated with scaler or arrays of same size can be used as scalar

In [34]:
array 

array([53, 28, 21, 70, 88, 14, 11, 86, 18, 41])

In [35]:
arr_copy

array([69, 69, 69, 69, 69])

In [36]:
array*arr_copy

ValueError: operands could not be broadcast together with shapes (10,) (5,) 

In [37]:
array_copy

array([100, 100, 100, 100, 100])

In [38]:
arr_copy*array_copy

array([6900, 6900, 6900, 6900, 6900])

In [39]:
arr_copy+array_copy

array([169, 169, 169, 169, 169])

In [40]:
array_copy+13

array([113, 113, 113, 113, 113])

In [ ]:
with numpy operations, 0/0 -> NaN
                       (value)/0 -> Inf

In [42]:
array = np.arange(0,2)
array

array([0, 1])

In [43]:
array/0

/var/folders/l8/_b6fjjrx2bd3sc4gf4vqf0vc0000gp/T/ipykernel_29380/2722579035.py:1: RuntimeWarning: divide by zero encountered in divide
  array/0
/var/folders/l8/_b6fjjrx2bd3sc4gf4vqf0vc0000gp/T/ipykernel_29380/2722579035.py:1: RuntimeWarning: invalid value encountered in divide
  array/0


array([nan, inf])

In [ ]:
Functions:
    np.sqrt(array)
    np.sin(array)
    np.log(array)
    array.sum(axis=) 0 for column, 1 for row
    array.mean()
    array.var()
    array.std()